apiVersion: v1
kind: Service
metadata:
  name: certificate-management-operator-metrics
  namespace: openshift-operators
  labels:
    control-plane: controller-manager
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    control-plane: controller-manager
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: certificate-management-operator-metrics
  namespace: openshift-operators
  labels:
    control-plane: controller-manager
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  selector:
    matchLabels:
      control-plane: controller-manager
